# Configuration for Automated Documentation Generator

# Directories to exclude from scanning
exclude_dirs:
  - node_modules
  - __pycache__
  - .git
  - .venv
  - venv
  - dist
  - build
  - .vscode
  - .idea
  - .pytest_cache
  - __pypackages__
  - .tox
  - .mypy_cache

# Output configuration
output:
  directory: Documentation
  format: markdown  # Currently only markdown supported
  include_toc: true
  
# LLM Configuration
llm:
  model: gemini-2.5-flash
  temperature: 0.3
  max_retries: 3
  timeout: 30
  rate_limit_calls_per_minute: 20
  
# Cache configuration
cache:
  enabled: true
  file: .docstring_cache.json
  
# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: docgen.log
  
# Processing configuration
processing:
  parallel: true
  max_workers: 4
  
# Security configuration
security:
  forbidden_paths:
    - /etc
    - /sys
    - /proc
    - ~/.ssh
  validate_paths: true